/**
 * Mirrors the Rust types in `src-tauri/src/session` and `src-tauri/src/error.rs`.
 *
 * These are hand-maintained for now. Milestone 3 replaces this file with types
 * generated by `ts-rs` so the contract cannot drift; until then, any change to
 * a Rust type must be reflected here and in `docs/ipc.md` in the same commit.
 */

export type SessionKind = "local";

export interface SessionInfo {
  sessionId: string;
  kind: SessionKind;
  title: string;
}

export interface SessionClosed {
  sessionId: string;
  reason: "exit" | "killed" | "error";
  exitCode: number | null;
}

export type ShellFamily = "windows" | "wsl" | "unix";

export interface ShellSpec {
  id: string;
  label: string;
  program: string;
  args: string[];
  family: ShellFamily;
  default: boolean;
}

/** Stable error codes; see `AppError::code` on the Rust side. */
export type AppErrorCode =
  | "SESSION_NOT_FOUND"
  | "ALREADY_SUBSCRIBED"
  | "SHELL_NOT_FOUND"
  | "PTY_OPEN_FAILED"
  | "SPAWN_FAILED"
  | "IO_ERROR"
  | "INTERNAL";

export interface AppError {
  code: AppErrorCode;
  message: string;
  details?: unknown;
}

export function isAppError(value: unknown): value is AppError {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as AppError).code === "string" &&
    typeof (value as AppError).message === "string"
  );
}

/** Human-readable fallback for anything thrown across the IPC boundary. */
export function errorMessage(value: unknown): string {
  if (isAppError(value)) return value.message;
  if (value instanceof Error) return value.message;
  return String(value);
}
