/**
 * Mirrors the Rust types in `src-tauri/src/session` and `src-tauri/src/error.rs`.
 *
 * These are hand-maintained for now. Milestone 3 replaces this file with types
 * generated by `ts-rs` so the contract cannot drift; until then, any change to
 * a Rust type must be reflected here and in `docs/ipc.md` in the same commit.
 */

export type SessionKind = "local" | "ssh";

export interface SessionInfo {
  sessionId: string;
  kind: SessionKind;
  title: string;
}

export interface SessionClosed {
  sessionId: string;
  reason: "exit" | "killed" | "error";
  exitCode: number | null;
}

export type ShellFamily = "windows" | "wsl" | "unix";

export interface ShellSpec {
  id: string;
  label: string;
  program: string;
  args: string[];
  family: ShellFamily;
  default: boolean;
}

// ---------------------------------------------------------------------------
// SSH
// ---------------------------------------------------------------------------

export interface SshTarget {
  host: string;
  port: number;
  user: string;
}

/**
 * One authentication method to try, in the order given. Mirrors
 * `AuthChoice` in `src-tauri/src/ssh/mod.rs`.
 */
export type AuthChoice =
  | { kind: "agent" }
  | { kind: "key"; path: string }
  | { kind: "password" }
  | { kind: "keyboardInteractive" };

/** A host key already on file, as shown in the host key prompt. */
export interface StoredKey {
  algorithm: string;
  fingerprint: string;
  /** The file it came from - the user's `known_hosts`, or Harbour's own. */
  source: string;
  line: number;
}

export type HostKeyStatus = "unknown" | "changed";

/** Payload of `connection:hostkey_prompt`. */
export interface HostKeyPrompt {
  promptId: string;
  host: string;
  port: number;
  status: HostKeyStatus;
  algorithm: string;
  fingerprint: string;
  /** What is already recorded: the key that changed, or keys of other types. */
  stored: StoredKey[];
}

export type SecretKind = "password" | "passphrase" | "challenge";

/** Payload of `connection:auth_prompt`. */
export interface SecretPrompt {
  promptId: string;
  host: string;
  user: string;
  kind: SecretKind;
  label: string;
  /** Server-supplied context under keyboard-interactive; empty otherwise. */
  instruction: string;
  /** True only when the server says the answer is not a secret. */
  echo: boolean;
  /**
   * Whether there is anywhere to save this answer: a saved host to attach it
   * to, on a machine with a usable keychain. False for an ad-hoc connection.
   */
  canRemember: boolean;
}

export interface HostKeyAnswer {
  accept: boolean;
  remember: boolean;
}

export interface SecretAnswer {
  /** `null` means the user dismissed the prompt. */
  secret: string | null;
  /** Save it in the OS keychain. Only ever set when `canRemember` was true. */
  remember: boolean;
}

// ---------------------------------------------------------------------------
// Vault
// ---------------------------------------------------------------------------

export interface Folder {
  id: string;
  /** `null` for a top-level folder. */
  parentId: string | null;
  name: string;
  position: number;
}

/** Which methods a saved host authenticates with, and in what order. */
export interface HostAuth {
  useAgent: boolean;
  keyPath: string | null;
  usePassword: boolean;
}

export interface Host {
  id: string;
  folderId: string | null;
  name: string;
  hostname: string;
  port: number;
  username: string;
  description: string | null;
  auth: HostAuth;
  /** Whether the OS keychain is expected to hold a password for this host. */
  hasSavedPassword: boolean;
  position: number;
}

/** The fields a caller may set; ids and positions belong to the store. */
export interface HostInput {
  folderId: string | null;
  name: string;
  hostname: string;
  port: number;
  username: string;
  description: string | null;
  auth: HostAuth;
}

export interface VaultTree {
  folders: Folder[];
  hosts: Host[];
}

/** One host an import found, and whether it can be brought across. */
export interface ImportCandidate {
  name: string;
  folder: string[];
  hostname: string;
  port: number;
  username: string | null;
  description: string | null;
  keyPath: string | null;
  usesPassword: boolean;
  /** Set when it cannot be imported, saying why. */
  skipReason: string | null;
}

export interface ImportPreview {
  candidates: ImportCandidate[];
  /** Anything the user should know that is not about one host. */
  notes: string[];
  source: string;
}

export interface ImportResult {
  hosts: number;
  skipped: number;
}

/** Stable error codes; see `AppError::code` on the Rust side. */
export type AppErrorCode =
  | "SESSION_NOT_FOUND"
  | "ALREADY_SUBSCRIBED"
  | "SHELL_NOT_FOUND"
  | "PTY_OPEN_FAILED"
  | "SPAWN_FAILED"
  | "IO_ERROR"
  | "SSH_CONNECT_FAILED"
  | "SSH_AUTH_FAILED"
  | "SSH_HOSTKEY_REJECTED"
  | "SSH_HOSTKEY_CHANGED"
  | "SSH_KEY_LOAD_FAILED"
  | "SSH_AGENT_UNAVAILABLE"
  | "SSH_CHANNEL_FAILED"
  | "SSH_PROTOCOL_ERROR"
  | "HOST_NOT_FOUND"
  | "FOLDER_NOT_FOUND"
  | "VAULT_ERROR"
  | "KEYRING_UNAVAILABLE"
  | "PROMPT_NOT_FOUND"
  | "PROMPT_TIMED_OUT"
  | "INTERNAL";

export interface AppError {
  code: AppErrorCode;
  message: string;
  details?: unknown;
}

export function isAppError(value: unknown): value is AppError {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as AppError).code === "string" &&
    typeof (value as AppError).message === "string"
  );
}

/** Human-readable fallback for anything thrown across the IPC boundary. */
export function errorMessage(value: unknown): string {
  if (isAppError(value)) return value.message;
  if (value instanceof Error) return value.message;
  return String(value);
}
